require('dotenv').config();

const express = require("express");
const Sequelize = require("sequelize");


/**
 * Connect to PostgreSQL database using Sequlize.
 * Generated by Sonnet4.5
 * 
 * @author claude.ai
*/
if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is required");
}
const sequelize = new Sequelize(process.env.DATABASE_URL, {
  // This parameter is what was generated to fix Dialect needing to be explicitly supplied
  dialect: "postgres",

});


const app = express();

app.use(express.static("public"));

const PORT = 3000;


app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});

app.get("/", (req, res) => {
  res.json({ message: "Hello World" });
  // res.redirect("/home");
});

sequelize

  .authenticate()

  .then(() => {
    console.log("Connection has been established successfully.");
  })

  .catch((err) => {
    console.error("Unable to connect to the database:", err);
  });